abb_irb120_3_58:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  gripper_finger_joint1_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_finger_joint1
    pid: {p: 700, i: 0.1, d: 1}    
  gripper_finger_joint2_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_finger_joint2
    pid: {p: 700, i: 0.1, d: 1}   
  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
    pid: {p: 100, i: 0.01, d: 10}
